name: fcl
channels:
  - conda-forge
  - nodefaults
dependencies:
  - eigen
  - octomap
  - assimp
  - numpy
  - boost
  - eigenpy
  - python
  - doxygen
  - lxml
  - pylatexenc
  - qhull
  - compilers=1.4.2  # [osx]
